version: "1.0"
triggers:
  - condition: "re:^diag:"
    target_mode: "diagnose"
    type: "HARD"
  - condition: "re:^impl:"
    target_mode: "implement"
    type: "HARD"
  - condition: "diagnose"
    target_mode: "diagnose"
    type: "SOFT"
  - condition: "implement"
    target_mode: "implement"
    type: "SOFT"
